[package]
name = "vault"
version = "1.0.0"
authors = []

[addresses]
vault = "0x27fc7d36a8946e85be9003fac9dbcb02e96e104d4d31c7e1c3f2c585d9fa7fef"
std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
