[package]
name = "vault"
version = "1.0.0"
authors = []

[addresses]
vault = "d2118781044cce8749b26cf366016f01eb0fdc7baa0e3a2b825e33b5fe8b2b46"
std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
