[package]
name = "governance"
version = "1.0.0"
authors = []

[addresses]
governance = "0x52969b2815d0b487a1ec923c01fa7faa203d6b790f0a6a83d5c39a66d63612d7"
std="0x1"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"


[dev-dependencies]
